"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass

@dataclass
class Relation:
    """An object representing a relation between two types registered with Oso."""
    kind: str
    other_type: str
    my_field: str
    other_field: str
    ...


def serialize_types(types, tmap): # -> dict[Unknown, Unknown]:
    """
    Convert types stored in python to what the core expects.
    """
    ...

