"""
This type stub file was generated by pyright.
"""

def get_python_error(err_str, enrich_message=...): # -> ExtraToken | IntegerOverflow | InvalidToken | InvalidTokenCharacter | UnrecognizedEOF | UnrecognizedToken | ParserError | UnsupportedError | PolarTypeError | StackOverflowError | PolarRuntimeError | UnknownError | OperationalError | ValidationError | None:
    """Fetch a Polar error and map it into a Python exception."""
    ...

