"""
This type stub file was generated by pyright.
"""

"""Exceptions used within Oso."""
class OsoError(Exception):
    """Base exception class for Oso."""
    def __init__(self, message=..., details=...) -> None:
        ...
    
    @classmethod
    def add_get_help(cls, message) -> str:
        ...
    


class FFIErrorNotFound(OsoError):
    """Raised when an error is generated by the Oso Rust core, but the error type is not found."""
    ...


class PolarRuntimeError(OsoError):
    """Errors generated by Oso at runtime"""
    ...


class UnsupportedError(PolarRuntimeError):
    """Unsupported action error generated by the Rust core"""
    ...


class PolarTypeError(PolarRuntimeError):
    """Error related to the type of a Polar object, generated by the Rust core"""
    ...


class StackOverflowError(PolarRuntimeError):
    """Polar stack overflow error, generated by the Rust core"""
    ...


class UnregisteredClassError(PolarRuntimeError):
    """Raised on attempts to reference unregistered Python classes from a Polar policy."""
    ...


class DuplicateClassAliasError(PolarRuntimeError):
    """Raised on attempts to register a class with the same name as a class that has already been registered"""
    def __init__(self, name, old, new) -> None:
        ...
    


class DuplicateInstanceRegistrationError(PolarRuntimeError):
    ...


class PolarFileExtensionError(PolarRuntimeError):
    def __init__(self, file) -> None:
        ...
    


class PolarFileNotFoundError(PolarRuntimeError):
    def __init__(self, file) -> None:
        ...
    


class UnregisteredInstanceError(PolarRuntimeError):
    ...


class InlineQueryFailedError(PolarRuntimeError):
    def __init__(self, source) -> None:
        ...
    


class UnexpectedPolarTypeError(PolarRuntimeError):
    ...


class InvalidQueryTypeError(PolarRuntimeError):
    ...


class InvalidCallError(PolarRuntimeError):
    """Invalid attempt to call a field or method on an object in Polar"""
    ...


class InvalidIteratorError(PolarRuntimeError):
    """Invalid attempt to iterate over a non-iterable value"""
    ...


class InvalidConstructorError(PolarRuntimeError):
    ...


class ParserError(OsoError):
    """Parse time errors."""
    ...


class IntegerOverflow(ParserError):
    ...


class InvalidTokenCharacter(ParserError):
    ...


class InvalidToken(ParserError):
    ...


class UnrecognizedEOF(ParserError):
    ...


class UnrecognizedToken(ParserError):
    ...


class ExtraToken(ParserError):
    ...


class OperationalError(OsoError):
    """Errors from polar that are not necessarily the user's fault. OOM etc..."""
    ...


class UnknownError(OperationalError):
    ...


class ValidationError(OsoError):
    ...


UNEXPECTED_EXPRESSION_MESSAGE = ...
