"""
This type stub file was generated by pyright.
"""

from typing import Any, Sequence

class Predicate:
    """Represent a predicate in Polar (`name(args, ...)`)."""
    name: str
    args: Sequence[Any]
    def __init__(self, name: str, args: Sequence[Any]) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __eq__(self, other: Any) -> bool:
        ...
    


