"""
This type stub file was generated by pyright.
"""

from typing import Any

class Variable(str):
    """An unbound variable type, can be used to query the KB for information"""
    def __repr__(self) -> str:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __eq__(self, other: Any) -> bool:
        ...
    
    def __hash__(self) -> int:
        ...
    


